---
collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: awx.awx
  - name: chocolatey.chocolatey
  - name: community.crypto
  - name: community.dns
  - name: community.docker
  - name: community.general
  - name: community.hashi_vault
  - name: community.mongodb
  - name: community.mysql
  - name: community.network
  - name: community.postgresql
  - name: community.vmware
    version: '<5.0.0'
  - name: community.windows
  - name: community.zabbix
  - name: containers.podman
  - name: fortinet.fortimanager
  - name: fortinet.fortios
  - name: google.cloud
  - name: microsoft.ad
  - name: vmware.vmware
  - name: vmware.vmware_rest
  - name: trippsc2.ad
  - name: trippsc2.adcs
  - name: trippsc2.cis
  - name: trippsc2.citrix
  - name: trippsc2.dfs
  - name: trippsc2.duo
  - name: trippsc2.first_steps
  - name: trippsc2.general
  - name: trippsc2.hashi_vault
  - name: trippsc2.mssql
  - name: trippsc2.packer
  - name: trippsc2.postgresql
  - name: trippsc2.template
  - name: trippsc2.vmware
  - name: trippsc2.windows
  - name: trippsc2.zabbix
