---
version: 3

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  ansible_core:
    package_pip: ansible-core>=2.17,<2.18
  ansible_runner:
    package_pip: ansible-runner
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12

images:
  base_image:
    name: docker.io/library/rockylinux:9-minimal

additional_build_files:
  - src: files/ansible.cfg
    dest: configs

additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg ~/.ansible.cfg
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.12 312

options:
  package_manager_path: /usr/bin/microdnf
